name: Trigger Render Deployment

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Create deployment
        uses: sws2apps/render-deployment@v1.6.0 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          node-version: lts/*  
          cli-version: 2.2.0   
      - name: Debug secrets
        run: |
          echo "SERVICE ID length: ${#RENDER_SERVICE_ID}"
          echo "API KEY length: ${#RENDER_API_KEY}"
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

