name: Test workflow

on: 
 push: 
  branches: 
   - main

jobs: 
 hello_world_test_job:
  runs-on: ubuntu-latest
  steps:
  - name: Say Hello
    run: |
     echo "Hello world"
  - name: Now it is
    run: |
     date
     echo $(date +%s)
  - name: Directory content
    run: |
     ls -l
     echo "total: $(ls -l)"
  
